version: '3.8'

services:
  fileid-bot:
    image: aiastia/fileid-bot:latest
    volumes:
      - ./data:/app/data/
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
      - BOT_TOKEN=${BOT_TOKEN}
      - ADMIN_IDS=${ADMIN_IDS:-}
    logging:
      options:
        max-size: "10m"
        max-file: "3"